name: Check code

on: push

jobs:
  check-code:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    container:
      image: composer:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing composer dependencies
        run: composer install

      - name: Code analyze / PHP Insights
        run: |
          ./vendor/bin/phpinsights \
          --no-interaction \
          --config-path="config/phpinsights.php"

      - name: Run tests
        run: ./vendor/bin/phpunit tests
